#ifndef COVIDSIM_COUNTRY_H_INCLUDED_
#define COVIDSIM_COUNTRY_H_INCLUDED_


#define MAX_HOUSEHOLD_SIZE 10
#define MAX_INTERVENTION_TYPES 1
#define MAX_INTERVENTIONS_PER_ADUNIT 10

#define ADUNIT_LOOKUP_SIZE 1000000
#define MAX_COUNTRIES 100
#define NUM_PLACE_TYPES 4
#define MAX_ADUNITS 3200

// Maximal absent time - used for array sizing
#define MAX_ABSENT_TIME 8

#define MAX_DIST 2000

#endif // COVIDSIM_COUNTRY_H_INCLUDED_
